title: jwoytas.github.io
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Working towards creating simple yet powerful static websites
  using GitHub Pages and Jekyll
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://jwoytas.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jwoytas
github_username:  jwoytas

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

theme: jekyll-theme-hacker
show_downloads: false

# Google Analytics
google_analytics: UA-162526456-1


collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

